/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBotStreamRouteImport } from './routes/api/bot/stream'
import { Route as ApiBotSnapshotRouteImport } from './routes/api/bot/snapshot'
import { Route as ApiBotCommandRouteImport } from './routes/api/bot/command'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotStreamRoute = ApiBotStreamRouteImport.update({
  id: '/api/bot/stream',
  path: '/api/bot/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotSnapshotRoute = ApiBotSnapshotRouteImport.update({
  id: '/api/bot/snapshot',
  path: '/api/bot/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotCommandRoute = ApiBotCommandRouteImport.update({
  id: '/api/bot/command',
  path: '/api/bot/command',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/bot/command': typeof ApiBotCommandRoute
  '/api/bot/snapshot': typeof ApiBotSnapshotRoute
  '/api/bot/stream': typeof ApiBotStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/bot/command': typeof ApiBotCommandRoute
  '/api/bot/snapshot': typeof ApiBotSnapshotRoute
  '/api/bot/stream': typeof ApiBotStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/bot/command': typeof ApiBotCommandRoute
  '/api/bot/snapshot': typeof ApiBotSnapshotRoute
  '/api/bot/stream': typeof ApiBotStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/bot/command'
    | '/api/bot/snapshot'
    | '/api/bot/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/bot/command'
    | '/api/bot/snapshot'
    | '/api/bot/stream'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/bot/command'
    | '/api/bot/snapshot'
    | '/api/bot/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiBotCommandRoute: typeof ApiBotCommandRoute
  ApiBotSnapshotRoute: typeof ApiBotSnapshotRoute
  ApiBotStreamRoute: typeof ApiBotStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot/stream': {
      id: '/api/bot/stream'
      path: '/api/bot/stream'
      fullPath: '/api/bot/stream'
      preLoaderRoute: typeof ApiBotStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot/snapshot': {
      id: '/api/bot/snapshot'
      path: '/api/bot/snapshot'
      fullPath: '/api/bot/snapshot'
      preLoaderRoute: typeof ApiBotSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot/command': {
      id: '/api/bot/command'
      path: '/api/bot/command'
      fullPath: '/api/bot/command'
      preLoaderRoute: typeof ApiBotCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiBotCommandRoute: ApiBotCommandRoute,
  ApiBotSnapshotRoute: ApiBotSnapshotRoute,
  ApiBotStreamRoute: ApiBotStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
